[workspace]
name = "flux-python"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
python = ">=3.8"
pip = "*"

[feature.py38.dependencies]
python = "3.8.*"
[feature.py39.dependencies]
python = "3.9.*"
[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[feature.common.dependencies]
cffi = "*"
pyyaml = "*"
jsonschema = "*"
docutils = "*"
ply = "*"
black = "*"
ipython = "*"
wheel = "*"
setuptools = "*"
luarocks = "*"
lua = "*"
lua-lpeg = "*"
libev = "*"
sphinx = "*"
libarchive = "*"
autoconf = "*"
automake = "*"
libtool = "*"
make = "*"
pkg-config = "*"
zeromq = "*"
jansson = "*"
libhwloc = "*"
libcxx = "*"
libsodium = "*"
argp-standalone = "*"
libuuid = "*"

[pypi-dependencies]
setuptools = "*"

[environments]
py38 = { features = ["py38", "common"] }
py39 = { features = ["py39", "common"] }
py310 = { features = ["py310", "common"] }
py311 = { features = ["py311", "common"] }
py312 = { features = ["py312", "common"] }
