name: build-legacy flux-python

on:
  pull_request: []
  workflow_dispatch:
    inputs:
      rc:
        description: 'Release candiate to target for wheels'
        default: "0"
      repo:
        description: 'Repository to build from'
        default: "https://github.com/rse-ops/flux-core-python"

jobs:
  build-manual:
    runs-on: ubuntu-latest
    container:
      image: fluxrm/testenv:focal
    steps:
    - uses: actions/checkout@v3

    - name: Build Flux Core Branch
      env:
        FLUX_RELEASE_VERSION: ${{ inputs.release_version }}
        FLUX_VERSION: ${{ inputs.version }}
      run: /bin/bash .github/scripts/setup.sh

    - name: Build Python Bindings
      env:
        FLUX_BRANCH: ${{ inputs.branch }}
        FLUX_REPO: ${{ inputs.repo }}
      run: |
        git clone -b ${FLUX_BRANCH} ${FLUX_REPO} /tmp/flux-core  || git clone https://github.com/flux-framework/flux-core /tmp/flux-core
        mv /tmp/flux-core/src/bindings/python/flux ./flux
        python3 setup.py sdist
        sudo ldconfig

    - name: Build Python Wheels
      run: |
        /bin/bash ./docker/install-mamba.sh
        /bin/bash ./docker/build-wheels.sh

    - name: Install dependencies
      if: (github.event_name != 'pull_request')
      run: python3 -m pip install setuptools wheel twine

    - name: Build and publish
      if: (github.event_name != 'pull_request')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
      run: twine upload dist/*
