name: build flux-python

on:
  push:
    branches:
      - doesnotexist

  # TODO this will trigger nightly to check for releases, not active yet
  # pull_request: []
  # schedule:
  #  - cron: "5 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      api:
        image: fluxrm/testenv:focal
    steps:
    - uses: actions/checkout@v3    
    # TODO add release check here to get version
    - name: Build Flux Core
      run: /bin/bash .github/scripts/setup.sh

    - name: Build Python Bindings
      run: |
        mv /code/src/bindings/python/flux ./flux
        python3 setup.py sdist bdist_wheel --flux-root /code --security-src $HOME/security --security-include /usr/local/include/flux/security --version develop
