name: test-build flux-python

on:
  pull_request: []
  schedule:
    - cron: "5 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fluxrm/testenv:focal
    steps:
    - uses: actions/checkout@v3

    - name: Build Flux Core
      env:
        FLUX_RELEASE_VERSION: "0.50.0"
      run: /bin/bash .github/scripts/setup.sh

    - name: Build Python Bindings
      run: |
        mv /code/src/bindings/python/flux ./flux
        python3 setup.py sdist
  
    - name: Build Python Wheels
      run: |
        /bin/bash ./docker/install-mamba.sh
        /bin/bash ./docker/build-wheels.sh